"use client";

import { useEffect, useMemo, useState } from "react";

type Asset={code:string;name:string;type:"个股"|"ETF";price:number;change:number;signal:"买入"|"持有"|"减仓";confidence:number;support:number;stop:number;target:number;data:number[];shares?:number;cost?:number};
type QuantResult={framework:string;bars:number;latest_date:string;commission:number;total_return:number;annual_return:number;max_drawdown:number;sharpe:number|null;trades:number;won:number;lost:number;signal:string;fast_ma:number;slow_ma:number};
type QuantSnapshot={generated_at:string|null;frequency_minutes:number;signals:Record<string,QuantResult>};
const QUANT_API="http://127.0.0.1:8000";
const QUANT_SNAPSHOT_URL=process.env.NEXT_PUBLIC_QUANT_SNAPSHOT_URL||"https://raw.githubusercontent.com/danielmd202506-debug/hengce-quant-lab/main/public/quant-signals.json";
const assets:Asset[]=[
 {code:"000965",name:"天保基建",type:"个股",price:3.12,change:-2.8,signal:"持有",confidence:60,support:3.06,stop:3,target:3.36,data:[3.44,3.39,3.36,3.31,3.28,3.24,3.19,3.22,3.18,3.16,3.21,3.17,3.14,3.19,3.15,3.12],shares:7200,cost:3.392},
 {code:"159755",name:"电池ETF广发",type:"ETF",price:.962,change:0,signal:"持有",confidence:58,support:.94,stop:.92,target:1.03,data:[1.08,1.06,1.04,1.05,1.02,1.01,.99,1,.98,.97,.99,.98,.96,.97,.95,.962],shares:7000,cost:1.11},
 {code:"159870",name:"化工ETF鹏华",type:"ETF",price:.811,change:0,signal:"持有",confidence:57,support:.79,stop:.77,target:.87,data:[.86,.85,.84,.85,.83,.82,.84,.83,.82,.81,.82,.8,.81,.82,.8,.811],shares:6800,cost:.852}
];
const secid=(code:string)=>`${/^[569]/.test(code)?1:0}.${code}`;
async function getLive(base:Asset):Promise<Asset>{
 const fields="f57,f58,f43,f170,f59";
 const [q,k]=await Promise.all([
  fetch(`https://push2.eastmoney.com/api/qt/stock/get?invt=2&fltt=1&secid=${secid(base.code)}&fields=${fields}`,{cache:"no-store"}).then(r=>r.json()),
  fetch(`https://push2his.eastmoney.com/api/qt/stock/kline/get?invt=2&fltt=1&secid=${secid(base.code)}&klt=101&fqt=1&lmt=60&end=20500101&fields1=f1,f2,f3,f4,f5,f6&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61`,{cache:"no-store"}).then(r=>r.json())
 ]);
 if(!q.data||!k.data?.klines?.length)throw new Error("未找到该证券代码");
 const decimals=q.data.f59??2, price=q.data.f43/10**decimals, closes:number[]=k.data.klines.map((x:string)=>Number(x.split(",")[2]));
 const recent=closes.slice(-20),ma5=closes.slice(-5).reduce((x,y)=>x+y,0)/5,ma20=recent.reduce((x,y)=>x+y,0)/recent.length,support=Math.min(...recent),momentum=(price/ma20-1)*100;
 const signal:Asset["signal"]=ma5>ma20&&momentum>1?"买入":ma5<ma20&&momentum<-1?"减仓":"持有"; const confidence=Math.min(84,Math.max(52,Math.round(60+Math.abs(momentum)*2)));
 return {...base,name:q.data.f58||base.name,price:+price.toFixed(decimals),change:+(q.data.f170/100).toFixed(2),signal,confidence,support:+support.toFixed(decimals),stop:+(support*.98).toFixed(decimals),target:+(price+(price-support*.98)*2).toFixed(decimals),data:closes};
}
function PriceChart({a}:{a:Asset}){const values=a.cost?[...a.data,a.cost]:a.data,min=Math.min(...values),max=Math.max(...values),pad=(max-min||max*.05||1)*.08,low=min-pad,high=max+pad,y=(v:number)=>55-(v-low)/(high-low)*50,pts=a.data.map((v,i)=>`${i/(a.data.length-1)*100},${y(v)}`).join(" "),costY=a.cost?y(a.cost):null,lastY=y(a.data.at(-1)??a.price),digits=a.price<10?3:2;return <><div className="chartKey"><span><i></i>收盘价</span>{a.cost&&<span><i className="costKey"></i>我的成本 ¥{a.cost.toFixed(3)}</span>}</div><div className="priceScale"><b>¥{max.toFixed(digits)}</b><b>¥{min.toFixed(digits)}</b></div><svg className="priceChart" viewBox="0 0 100 60" preserveAspectRatio="none" aria-label={`${a.name}最近20个交易日收盘价走势`}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#c9523c" stopOpacity=".18"/><stop offset="1" stopColor="#c9523c" stopOpacity="0"/></linearGradient></defs>{costY!==null&&<line x1="0" y1={costY} x2="100" y2={costY} stroke="#6e7d82" strokeWidth=".7" strokeDasharray="3 2"/>}<polygon points={`0,60 ${pts} 100,60`} fill="url(#fill)"/><polyline points={pts} fill="none" stroke="#c9523c" strokeWidth="1.3" vectorEffect="non-scaling-stroke"/><circle cx="100" cy={lastY} r="1.2" fill="#c9523c" vectorEffect="non-scaling-stroke"/></svg></>}
export default function Home(){
 const [list,setList]=useState<Asset[]>(assets),[kind,setKind]=useState<"全部"|"个股"|"ETF">("全部"),[selected,setSelected]=useState(0),[query,setQuery]=useState(""),[scanning,setScanning]=useState(false),[adding,setAdding]=useState(false),[liveTime,setLiveTime]=useState(""),[liveError,setLiveError]=useState(""),[quantResult,setQuant]=useState<QuantResult|null>(null),[quantCode,setQuantCode]=useState(""),[quantError,setQuantError]=useState("");
 const [draft,setDraft]=useState({code:"",name:"",type:"个股" as "个股"|"ETF"});
 useEffect(()=>{try{const saved:Asset[]=JSON.parse(localStorage.getItem("hengce-watchlist")||"[]");const restored=assets.map(base=>{const old=saved.find(x=>x.code===base.code);return old?{...old,shares:base.shares,cost:base.cost,type:base.type}:base});setList(restored);localStorage.setItem("hengce-watchlist",JSON.stringify(restored))}catch{setList(assets)}setSelected(0)},[]);
 useEffect(()=>{let active=true;Promise.allSettled(assets.filter(x=>x.shares).map(getLive)).then(results=>{if(!active)return;const fresh=results.filter((x):x is PromiseFulfilledResult<Asset>=>x.status==="fulfilled").map(x=>x.value);setList(old=>old.map(x=>fresh.find(y=>y.code===x.code)||x))});return()=>{active=false}},[]);
 useEffect(()=>{let active=true;async function refresh(){setScanning(true);setLiveError("");try{const next=await getLive(list[selected]||list[0]);if(active){setList(old=>{const updated=old.map((x,i)=>i===selected?next:x);localStorage.setItem("hengce-watchlist",JSON.stringify(updated));return updated});setLiveTime(new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}))}}catch(e){if(active)setLiveError(e instanceof Error?e.message:"行情获取失败")}finally{if(active)setScanning(false)}}refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[selected]);
 useEffect(()=>{let active=true;const current=list[selected]||assets[0],commission=current.type==="ETF"?0.00005:0.000086;if(current.data.length<22)return;setQuant(null);setQuantCode(current.code);setQuantError("");async function loadQuant(){try{const snapshot:QuantSnapshot=await fetch(`${QUANT_SNAPSHOT_URL}?t=${Date.now()}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error();return r.json()});const saved=snapshot.signals?.[current.code];if(saved){if(active){setQuant(saved);setQuantCode(current.code)}return}}catch{}try{const data=await fetch(`${QUANT_API}/backtest`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:current.code,closes:current.data,fast:5,slow:20,commission})}).then(r=>{if(!r.ok)throw new Error();return r.json()});if(active){setQuant(data);setQuantCode(current.code)}}catch{if(active)setQuantError(`暂无 ${current.name} 的量化快照`)}}loadQuant();return()=>{active=false}},[selected,list[selected]?.data]);
 const filtered=list.filter(a=>(kind==="全部"||a.type===kind)&&(a.name.includes(query)||a.code.includes(query))); const a=list[selected]||list[0],quant=quantCode===a.code?quantResult:null;
 const outlook=useMemo(()=>({up:a.confidence,side:Math.max(12,82-a.confidence),down:18}),[a]);
 const holding=a.shares&&a.cost?{costValue:a.shares*a.cost,marketValue:a.shares*a.price,pnl:a.shares*(a.price-a.cost),pnlPct:(a.price/a.cost-1)*100}:null;
 const maGap=quant&&quant.slow_ma?((quant.fast_ma/quant.slow_ma-1)*100):null,winRate=quant&&quant.trades?quant.won/quant.trades*100:null;
 const strategyWeak=!!quant&&(quant.total_return<0||(quant.sharpe??0)<0||quant.max_drawdown>30);
 const portfolio=useMemo(()=>{const held=list.filter(x=>x.shares&&x.cost),market=held.reduce((s,x)=>s+x.price*x.shares!,0),cost=held.reduce((s,x)=>s+x.cost!*x.shares!,0);return{count:held.length,market,cost,pnl:market-cost,pnlPct:(market/cost-1)*100,assets:market+375.92}},[list]);
 async function scan(){setScanning(true);setLiveError("");try{const next=await getLive(a);setList(old=>old.map((x,i)=>i===selected?next:x));setLiveTime(new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}))}catch(e){setLiveError(e instanceof Error?e.message:"行情获取失败")}finally{setScanning(false)}}
 function saveList(next:Asset[]){setList(next);localStorage.setItem("hengce-watchlist",JSON.stringify(next))}
 async function addAsset(e:React.FormEvent){e.preventDefault();if(!/^\d{6}$/.test(draft.code.trim())){setLiveError("请输入 6 位证券代码");return}setScanning(true);try{const empty:Asset={code:draft.code.trim(),name:draft.name.trim()||draft.code.trim(),type:draft.type,price:0,change:0,signal:"持有",confidence:50,support:0,stop:0,target:0,data:[40,45]};const item=await getLive(empty);const next=[...list.filter(x=>x.code!==item.code),item];saveList(next);setSelected(next.length-1);setAdding(false);setDraft({code:"",name:"",type:"个股"});setLiveTime(new Date().toLocaleTimeString("zh-CN"));setLiveError("")}catch(e){setLiveError(e instanceof Error?e.message:"无法获取该证券行情")}finally{setScanning(false)}}
 function removeAsset(index:number){if(list.length===1)return;const next=list.filter((_,i)=>i!==index);saveList(next);setSelected(Math.min(selected,next.length-1))}
 return <main><aside><div className="brand"><span>衡</span><div>衡策<br/><small>QUANT LAB</small></div></div><nav><a className="active">⌁ <span>买卖信号</span></a><a>◎ <span>我的自选</span></a><a>▥ <span>回测记录</span></a><a>▦ <span>策略设置</span></a></nav><div className="asideFoot"><a>⚙ <span>数据与偏好</span></a><div className="avatar">D</div><div><b>模拟研究账户</b><small>不连接真实交易</small></div></div></aside>
 <section className="workspace"><header><div><p className="eyebrow">STOCK & ETF SIGNALS</p><h1>我的持仓操作台</h1><p>先看账户风险，再看每一笔持仓的操作信号。</p></div><div className="status live"><i></i> 真实行情 {liveTime&&`· ${liveTime} 更新`}</div></header>
 <section className="portfolioSummary"><div><small>账户总资产</small><b>¥{portfolio.assets.toLocaleString("zh-CN",{maximumFractionDigits:2})}</b><em>含可用资金 ¥375.92</em></div><div><small>持仓市值</small><b>¥{portfolio.market.toLocaleString("zh-CN",{maximumFractionDigits:2})}</b><em>{portfolio.count} 只持仓</em></div><div><small>持仓盈亏</small><b className={portfolio.pnl>=0?"rise":"fall"}>{portfolio.pnl>=0?"+":""}¥{portfolio.pnl.toLocaleString("zh-CN",{maximumFractionDigits:2})}</b><em className={portfolio.pnl>=0?"rise":"fall"}>{portfolio.pnlPct.toFixed(2)}%</em></div><div><small>仓位比例</small><b>{(portfolio.market/portfolio.assets*100).toFixed(1)}%</b><em>可用资金较低</em></div></section>
 <div className="assetLayout"><section className="panel watch"><div className="watchHead"><div className="assetTabs">{(["全部","个股","ETF"] as const).map(x=><button className={kind===x?"on":""} onClick={()=>setKind(x)} key={x}>{x}</button>)}</div><div className="search"><span>⌕</span><input aria-label="搜索持仓" placeholder="搜索我的持仓" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="watchLabel"><span>我的持仓</span><small>{filtered.length} 个</small></div><div className="assetList">{filtered.map(item=>{const i=list.indexOf(item);return <div className="assetRow" key={item.code}><button className={selected===i?"asset active":"asset"} onClick={()=>{setSelected(i);setQuant(null);setQuantCode(item.code);setQuantError("")}}><div><b>{item.name}</b><small>{item.code} · {item.type}</small></div><div className="quote"><b>{item.price}</b><small className={item.change>=0?"rise":"fall"}>{item.change>=0?"+":""}{item.change}%</small></div><em className={`badge ${item.signal}`}>{item.signal}</em></button></div>})}</div></section>
 <section className="detail"><div className="panel hero"><div className="assetTitle"><div><small>{a.code} · {a.type}</small><h2>{a.name}</h2></div><div className="livePrice"><b>{a.price}</b><span className={a.change>=0?"rise":"fall"}>{a.change>=0?"+":""}{a.change}%</span></div></div>{holding&&<div className="holdingStrip"><div><small>我的持仓</small><b>{a.shares?.toLocaleString()} 股</b></div><div><small>成本价</small><b>¥{a.cost?.toFixed(3)}</b></div><div><small>持仓市值</small><b>¥{holding.marketValue.toLocaleString("zh-CN",{maximumFractionDigits:2})}</b></div><div><small>浮动盈亏</small><b className={holding.pnl>=0?"rise":"fall"}>{holding.pnl>=0?"+":""}¥{holding.pnl.toLocaleString("zh-CN",{maximumFractionDigits:2})} <em>({holding.pnlPct.toFixed(2)}%)</em></b></div></div>}<div className="chartArea"><PriceChart a={{...a,data:a.data.slice(-20)}}/><div className="chartDates"><span>最近20个交易日</span><span>每日收盘价</span><span>{liveTime||"更新中"}</span></div></div></div>
 <div className="decisionRow"><div className="panel decision"><div className="sectionTitle"><span>01</span><h3>Backtrader 当前信号</h3><small className={quant?"engineOnline":"engineOffline"}>{quant?`已连接 · ${quant.bars}日回测`:quantError||"正在连接"}</small></div><div className="decisionMain"><div className={`signalOrb ${quant?.signal.includes("减仓")?"减仓":quant?.signal.includes("买入")?"买入":"持有"}`}>{quant?.signal||"计算中"}</div><div><p>MA5 / MA20 · 5日线相对20日线</p><strong>{quant?`${quant.fast_ma} / ${quant.slow_ma}`:"—"}</strong>{maGap!==null&&<small className="maGap">仅高出 {maGap.toFixed(2)}%，趋势力度较弱</small>}</div><div className="position"><small>回测框架 · 实际佣金</small><b>{quant?`${quant.framework} · 万${(quant.commission*10000).toFixed(2)}`:"Backtrader"}</b></div></div>{quant&&<div className={`strategyVerdict ${strategyWeak?"weak":"good"}`}><b>{strategyWeak?"历史策略表现较差，不支持仅凭均线加仓":"历史策略表现尚可，仍需结合价格与仓位"}</b><span>{strategyWeak?"当前建议：等待观察，不把回测结果当作确定预测。":"当前信号只作研究参考，不代表未来收益。"}</span></div>}<div className="quantMetrics"><span>累计收益 <b className={(quant?.total_return||0)>=0?"rise":"fall"}>{quant?`${quant.total_return}%${quant.total_return<0?"（亏损）":"（盈利）"}`:"—"}</b></span><span>年化收益 <b className={(quant?.annual_return||0)>=0?"rise":"fall"}>{quant?`${quant.annual_return}%`:"—"}</b></span><span>最大回撤 <b className={(quant?.max_drawdown||0)>30?"riskText":""}>{quant?`${quant.max_drawdown}%`:"—"}</b></span><span>夏普比率 <b className={(quant?.sharpe||0)<0?"riskText":""}>{quant?.sharpe??"—"}</b></span><span>完成交易 <b>{quant?.trades??"—"} 笔</b></span><span>胜率 <b>{winRate!==null?`${winRate.toFixed(1)}%（${quant?.won}胜/${quant?.lost}负）`:"—"}</b></span></div><p className="metricNote">累计收益、回撤和胜率来自历史模拟，不是你当前持仓的实际盈亏。</p></div>
 <div className="panel levels"><div className="sectionTitle"><span>02</span><h3>操作价格参考</h3></div><div className="level buy"><small>观察买入区</small><b>{a.support} — {(a.support*1.012).toFixed(2)}</b><p>回踩支撑且量能稳定时分批考虑</p></div><div className="level"><small>止损参考</small><b>≤ {a.stop}</b><p>收盘跌破后重新评估趋势</p></div><div className="level target"><small>分批止盈区</small><b>≥ {a.target}</b><p>触及压力位后逐步锁定收益</p></div></div></div>
 <div className="panel forecast"><div className="sectionTitle"><span>03</span><h3>未来 20 个交易日情景</h3><small>概率估计，不是价格承诺</small></div><div className="scenarioGrid"><div><div className="scenarioTop"><span>上涨情景</span><b>{outlook.up}%</b></div><div className="bar"><i style={{width:`${outlook.up}%`}}></i></div><p>目标区间 {a.price} — {a.target}</p></div><div><div className="scenarioTop"><span>震荡情景</span><b>{outlook.side}%</b></div><div className="bar neutral"><i style={{width:`${outlook.side}%`}}></i></div><p>围绕当前价格上下波动</p></div><div><div className="scenarioTop"><span>下跌情景</span><b>{outlook.down}%</b></div><div className="bar down"><i style={{width:`${outlook.down}%`}}></i></div><p>重点观察止损位 {a.stop}</p></div></div><button className="scan" onClick={scan} disabled={scanning}>{scanning?"正在重新计算信号…":"重新计算操作信号  →"}</button></div>
 </section></div>{liveError&&<div className="errorToast">{liveError}</div>}<footer>行情来自公开市场数据接口；Backtrader 按股票万0.86、ETF万0.5计算佣金，暂不设最低5元。历史回测不代表未来收益。</footer></section>{adding&&<div className="modalBack" onMouseDown={e=>{if(e.currentTarget===e.target)setAdding(false)}}><form className="addModal" onSubmit={addAsset}><div className="modalTitle"><div><small>ADD TO WATCHLIST</small><h2>添加个股或 ETF</h2></div><button type="button" onClick={()=>setAdding(false)}>×</button></div><label>证券代码<input autoFocus inputMode="numeric" maxLength={6} placeholder="例如 600036 或 510050" value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.replace(/\D/g,"")})}/></label><label>证券名称（选填）<input placeholder="留空将自动读取真实名称" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>类型<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as "个股"|"ETF"})}><option>个股</option><option>ETF</option></select></label><p>添加后自动读取最新价格、涨跌幅和近 60 个交易日日线，不需要手填价格。</p>{liveError&&<div className="formError">{liveError}</div>}<div className="modalActions"><button type="button" onClick={()=>setAdding(false)}>取消</button><button type="submit" disabled={scanning}>{scanning?"正在读取行情…":"添加并读取真实行情"}</button></div></form></div>}</main>
}
